### ISSUE TITLE
iOS 10 compatibility with deprecated enum, compatibility with swift 2.3

### ISSUE THREAD

**Issue by heewoonam** [NordicSemiconductor/IOS-DFU-Library#50]
At DFUPeripheral.swift,  
logCentralManagerState(central.state) throws an error:
Cannot convert value of type 'CBManagerState' to expected argument type 'CBCentralManagerState'
also, there are some issues with migrating to swift 2.3 from Xcode 7 to Xcode 8.
This all happened after installing Xcode 8 to support iOS 10.
Any fix for this?

**Comment by mostafaberg** [comment]
It's no longer called `CBCentralManagerState` in Swift 2.3 and above, it's called `CBCentralState`
I would recommend migrating to Swift 3.0 instead of 2.3

We have updated this library on [Cocoapods](https://cocoapods.org/pods/iOSDFULibrary) Which is already in Swift 3.0 and you don't have to worry about code migration.
