### ISSUE TITLE
DFU Error - Writing to characteristic failed

### ISSUE THREAD

**Issue by furueili** [NordicSemiconductor/IOS-DFU-Library#51]
The DFUServiceDelegate never receives a DFUStateCompleted event with version 2.1.1 of the library. During a flashing update, the delegate receives these state changes: DFUStateConnecting, DFUStateStarting, DFUStateUploading.
Please give me some help thx
![2016-10-05 3 55 54](https://cloud.githubusercontent.com/assets/1407724/19105564/3381ddd0-8b15-11e6-81f9-fb761e9c21b2.png)

**Comment by mostafaberg** [comment]
Hey @furueili !, sorry for the inconvenience, first of all since you mentioned using version `2.1.1` that means you are posting in the wrong repository since the last version here is `1.0.8`.

If you are using that Cocoapods library can you please [post this question there](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library) instead of here ?

Then we can take it from there, thanks :)
