### ISSUE TITLE
Update fails without the corresponding DFUServiceDelegate state update

### ISSUE THREAD

**Issue by joonaservald** [NordicSemiconductor/IOS-DFU-Library#516]
**DFU Bootloader version:**
 - Bonding used: no
 - Library version: 4.13.0

**Device information:**
 - Device: iPhone 12
 - OS: iOS 17.1.1

**Describe the bug**
During a firmware update with the library, I am running into a case where the update fails but the `DFUServiceDelegate` method `dfuStateDidChange` does not return the `aborted` case. During this case, I was logging out both state updates from `dfuStateDidChange` and errors from `dfuError`, more on that below. I would expect that if the update fails for any reason, the state would change to `aborted` or similar.

**Logs**
The state and error updates come in the following order: 
- DFUServiceDelegate method `dfuStateDidChange` update: `starting`
- DFUServiceDelegate method `dfuStateDidChange` update: `enablingDfuMode`
- DFUServiceDelegate method `dfuError` update: `Error 4: Operation failed`
- LoggerDelegate method `logWith` update: `Disconnected`

After this, nothing. The last known `DFUServiceDelegate` state update was `enablingDfuMode` and not `aborted`.

**Comment by philips77** [comment]
Hello, 

This is kinda by design. I updated the doc now, but even before it was saying that whan an error is received that's all you get.  The state won't change. The state goes to `.aborted` only when DFU was explicitly aborted using the controller.

We may think about changing that, but that would be a breaking change, I think.
