### ISSUE TITLE
performDFUOnFile fails if called immediately after connecting to DFU device

### ISSUE THREAD

**Issue by Monix** [NordicSemiconductor/IOS-DFU-Library#8]
We've used this library to create an automatic firmware upgrade flow for a product and found that if we try to initiate the performDFUOnFile call immediately after connecting to the device, that it will fail with opcode 3, statys 6 (operation failed):

> Notification received from 00001534-1212-EFDE-1523-785FEABCD123, value (0x):100306

Eventually we worked out that if we added a delay of at least 1.5 seconds that it would work reliably.

Looking at other sample code (including nRFToolbox) it appears this issue is avoided because the performDFUOnFile is being manually triggered, allowing a natural delay.

We suspect the same issue exists in the Android library, but is less pronounced because the Android bluetooth stacks generally take longer to connect than iOS (thus giving the device enough time to get ready after connecting)

At the very least the gotcha should be documented somewhere, but it would be great if the library wouldn't execute the call until the device is ready for it, or had a callback to denote device ready.

**Comment by philips77** [comment]
Hi,
Do I understand correctly:
1. the performDFUOnFile is a method in your app, that triggers the DFUServiceInitiator?
If so, it should connect automatically... but you're saying that you call it after you connect. So it means you just used the modified library code in your app, instead of using the library as is.
2. So you're saying, that after connecting to a DFU bootloader (reading DFU Version with version != 0x0100) it should wait for 1.5 sec just to be sure. That's implementable :)
3. In nRF Toolbox 3.0 (the GitHub version, which should be available on AppStore soon) the performDFU is manually triggered, but it connects after you click Upload. It also reconnects to Bootloader automatically, without any delay, and it works at least on my desk :)
